- name: "create files"
  hosts: "web"
  become: true
  vars: 
    filecontent: "hello devops"
  tasks:
    - name: "manage all files"
      copy:
        content: "{{ item.text }}"
        dest: "{{ item.name }}"
      loop:
        - name: "/tmp/myfile1"
          text: "hiii hello"
        - name: "/tmp/myfile2"
          text: "hello 2"
        - name: "/tmp/anotherfile"
          text: "hello 3"