- name: "create files"
  hosts: "all"
  become: true
  vars:
    allowed: "yes"
  tasks: 
    - name: "Print th FQDN only if it is web host"
      debug:
        msg: "the FQDN for the hosts is {{ ansible_fqdn }}"
      when: ansible_hostname == "ip-172-31-63-228"
    
    - name: "install a package if allowed"
      apt: 
        name: "finger"
      when: allowed == "yes"