- name: Install WordPress and dependencies
  hosts: db
  become: yes
  vars:
    wp_version: 6.1.1
    wp_db_name: wp_project
    wp_db_user: wp_project
    wp_db_password: wp_project
  tasks:
  - name: Check and install required packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apache2
      - ghostscript
      - libapache2-mod-php
      - mysql-server
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
      - python3
      - python3-pip
  - name: Make sure pymysql is present
    become: true # needed if the other tasks are not played as root
    pip:
      name: pymysql
      state: present
  - name: Create MySQL database and user
    mysql_user:
      name: "{{ wp_db_user }}"
      password: "{{ wp_db_password }}"
      priv: "{{ wp_db_name }}.*:ALL"
      state: present
      login_user: root
      login_password: ""
      login_unix_socket: /var/run/mysqld/mysqld.sock
      host: localhost
  - name: Download WordPress
    get_url:
      url: https://wordpress.org/latest.zip
      dest: /tmp/wordpress.zip
  - name: Extract WordPress
    unarchive:
      src: /tmp/wordpress.zip
      dest: /var/www/html
      remote_src: yes
  - name: Configure WordPress
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wp-config.php
    vars:
      wp_tem_db_name: "{{ wp_db_name }}"
      wp_tem_db_user: "{{ wp_db_user }}"
      wp_tem_db_password: "{{ wp_db_password }}"
  - name: Start Apache Web Server
    service:
      name: apache2
      state: started
  - name: Print server IP address
    debug:
      msg: "Server IP address is {{ ansible_default_ipv4.address }}"
  - name: Validate installation
    uri:
      url: http://{{ ansible_default_ipv4.address }}
      status_code: 200